#include "server-cli.h"

ServerCLI::ServerCLI():CmdLineInterface("server>")
{
    console.log("Simple POP3-V2 Server v1.0\n");
    initCmd();
    pop3V2 = new Pop3V2Server(21);
    if(!pop3V2->configServer())
    {
        console.error("Cannot load server configuration");
        delete pop3V2;
        exit(-1);
    }

}
ServerCLI::~ServerCLI()
{
    delete pop3V2;
}

void ServerCLI::initCmd()
{
    addCmd("start",CLI_CAST(&ServerCLI::doStart));
    addCmd("stop",CLI_CAST(&ServerCLI::doStop));
    addCmd("help", CLI_CAST(&ServerCLI::doHelp));
    addCmd("signup", CLI_CAST(&ServerCLI::doSignUp));
    addCmd("addmail", CLI_CAST(&ServerCLI::doAddMail));
    addCmd("addmaildemo", CLI_CAST(&ServerCLI::doAddMailDemo));
}

void ServerCLI::doStart(std::string cmd_argv[], int cmd_argc)
{
    if(pop3V2->isRunning())
        console.running("POP3-V2 server is running!");
    else if(pop3V2->start())
        console.success("POP3-V2 Server started");
    else
        console.error("POP3-V2 Server failed to start");
}

void ServerCLI::doStop(std::string cmd_argv[], int cmd_argc)
{
    pop3V2->stop();
    console.stopping("POP3-V2 Server stopped");
}

void ServerCLI::doHelp(std::string cmd_argv[], int cmd_argc)
{
    console.log("Cac lenh cua chuong trinh: \n");
    console.log("- start               Bat server\n");
    console.log("- stop                Tat server\n");
    console.log("- help                ho tro\n");
    console.log("- signup <username> <password>              tao tai khoan\n");
    console.log("- addmail             them mail\n");
    console.log("- addmaildemo         them mail demo\n");
}

void ServerCLI::doSignUp(std::string cmd_argv[], int cmd_argc) {
    if (this->pop3V2->pop3V2Conf->createAccount(cmd_argv[1], cmd_argv[2])) {
        this->pop3V2->pop3V2Conf->loadAccountsFromDB();
        console.success("Create user: " + cmd_argv[1]);
    } else {
        console.error("Create fail");
    }
}

void ServerCLI::doAddMail(std::string cmd_argv[], int cmd_argc) {
    // Cú pháp: addmail <userId> <subject> <body>
    // cmd_argv[0] là "addmail"
    
    if (cmd_argc < 4) {
        console.error("Usage: addmail <userId> <subject> <body>");
        console.log("Note: UIDL is auto-generated by server.");
        return;
    }

    try {
        int userId = std::stoi(cmd_argv[1]);
        std::string subject = cmd_argv[2];
        
        // Xử lý Body: Nối tất cả các tham số còn lại thành 1 chuỗi
        std::string body = "";
        for (int i = 3; i < cmd_argc; ++i) {
            body += cmd_argv[i];
            if (i < cmd_argc - 1) body += " "; // Thêm dấu cách giữa các từ
        }

        // Gọi hàm helper
        this->helperAddMail(userId, subject, body);

    } catch (const std::exception& e) {
        console.error("Invalid arguments. UserID must be a number.");
    }
}

void ServerCLI::doAddMailDemo(std::string cmd_argv[], int cmd_argc) {
    int userId;
    int choice;

    console.log("\n--- DEMO MAIL GENERATOR ---\n");
    console.log("1. Welcome Mail (Chao mung thanh vien moi)\n");
    console.log("2. Security Alert (Canh bao dang nhap)\n");
    console.log("3. Promotion (Khuyen mai 50%)\n");
    console.log("---------------------------\n");

    // 1. Nhập User ID
    std::cout << "Enter User ID to receive mail: ";
    if (!(std::cin >> userId)) {
        console.error("Invalid User ID!");
        std::cin.clear(); std::cin.ignore(1000, '\n'); // Xóa bộ đệm
        return;
    }

    // 2. Nhập lựa chọn
    std::cout << "Select mail type (1-3): ";
    if (!(std::cin >> choice)) {
        console.error("Invalid selection!");
        std::cin.clear(); std::cin.ignore(1000, '\n');
        return;
    }
    
    // Xóa ký tự xuống dòng thừa trong bộ đệm để tránh lỗi CLI sau này
    std::cin.ignore(1000, '\n');

    std::string subject, body;

    switch (choice) {
        case 1:
            subject = "Welcome to POP3 Server";
            body = "Chao mung ban den voi he thong Email cua chung toi.\nHay trai nghiem dich vu nhe!";
            break;
        case 2:
            subject = "[Security] Login Alert";
            body = "Chung toi phat hien mot lan dang nhap la vao tai khoan cua ban.\nVui long kiem tra lai.";
            break;
        case 3:
            subject = "Black Friday Sale";
            body = "Giam gia 50% cho tat ca cac mat hang.\nChi duy nhat hom nay!";
            break;
        default:
            console.error("Unknown choice. Operation cancelled.");
            return;
    }

    // Gọi hàm helper
    console.log("Generating demo mail...");
    this->helperAddMail(userId, subject, body);
}

void ServerCLI::helperAddMail(int userId, std::string subject, std::string body) {
    // 1. Thêm vào Database
    Mail m;
    m.userId = userId;
    m.subject = subject;
    m.body = body;
    m.receivedAt = std::time(nullptr);

    m.mailId = this->pop3V2->pop3V2Conf->addMailToDB(m);
    if (this->pop3V2->pop3V2Conf->addMailToDB(m)) {
        console.success("Saved mail to Database for UserID: ", userId);
    } else {
        console.error("Failed to save mail to Database!");
        return;
    }

    // 2. Bơm vào Queue
    if (this->pop3V2->pop3V2Conf->getAccountLockedStatus(userId)) {
        MailInfo info;
        info.mailId = m.mailId;
        info.header = m.subject;
        
        this->pop3V2->pop3V2Conf->addMailToUserQueue(userId, info);
        console.info("Pushed mail to Active Session Queue for UserID: ", userId);
    } else {
        console.warn("User is offline. Mail will be synced next login.");
    }
}